### ISSUE TITLE
Messages::get() does not expect to get NULL as the second argument

### ISSUE THREAD

**Issue by rugabarbo** [D3strukt0r/votifier-client-php#1]
See:

https://github.com/D3strukt0r/votifier-client-php/blob/a69d6ca47915ea87d55e81ecdbd9140e0a37aa5d/src/ServerType/NuVotifier.php#L149

There will be an error while executing this line.

**Comment by D3strukt0r** [comment]
Thanks I'll have a look at it

**Comment by D3strukt0r** [comment]
Anyways, it's done now. Using `Messages::NOT_RECEIVED_PACKAGE` in that place was wrong anyways. I'll close this issue in the next few days, in case you still want to say something :)
